### PR TITLE
Add AI_Algorithms_with_java 

### PR DESCRIPTION
**Pull request by Adidem23**
I have Added Some Algorithms of AI in Java which are 
- BFS Traversal 
- Greedy_Search 
- Constraint Satisfication Problem
- Tic_tac_toe 

As Per The Issue #6 In the repository

### CODE REVIEW

**Review by d-coder111 — CHANGES_REQUESTED** [review]
Delete problems.txt file..rest is ok👍.
Kindly show your support by starring the repository! ⭐😊

**Comment by Adidem23** [comment]
I will do it Thank You bro @d-coder111 !!

**Comment by d-coder111** [comment]
Hey @Adidem23 ,
You have added valid programs..just delete txt file and I will merge it.

**Review by d-coder111 — COMMENTED** [review]
Looks Great🚀✌..Keep coding..Happy learning😊.
Do give it a star if it helped u to begin with as a beginner🌟.

**Comment by Adidem23** [comment]
I think I have Deleted text File Please Check @d-coder111 bro . If not I will do it

**Review by d-coder111 — APPROVED** [review]

**Pull request merged**
