### PR TITLE
Cycle Start Node finding algorithm added in JAVA

### PR DESCRIPTION
**Pull request by sohamt-21**
Here i have added an algorithm to find cycle start node of linked list with mathematical explanation on how it works along with figures in JAVA.

### CODE REVIEW

**Comment by sohamt-21** [comment]
Revert it, some changes required . Sorry for the inconvenience.

**Comment by sohamt-21** [comment]
@d-coder111

**Comment by d-coder111** [comment]
> Revert it, some changes required . Sorry for the inconvenience.

? are u done doing changes?

**Comment by sohamt-21** [comment]
Yes

**Review by d-coder111 — APPROVED** [review]

**Pull request merged**
