### PR TITLE
Update index.html and change the program structure

### PR DESCRIPTION
**Pull request by baranwalayush**
<h3> Issue Number 154 </h3>
<ol>
<li> Changed the program structure to make the project look more professional. 
<li> Updated the index.html file to have same style like about page and added a drop down menu to select among programming languages of which the user want answers.
<li> Changed the nav bar to have separate web page for contributor detail.
</ol>

<p>After this, I will create new issue to make the website functional.</p>

### CODE REVIEW

**Comment by d-coder111** [comment]
Kindly star the repo to show your support ✨.

**Review by d-coder111 — CHANGES_REQUESTED** [review]
Do not change the program structure.

**Comment by baranwalayush** [comment]
Ok, if you say then i will not change it, but i will need to make the template folder to work on the backend. And it would be better to work if the program structure will follow the general trends.

**Comment by baranwalayush** [comment]
Will it work for you, if I do not change the structure of the cpp, python and Java folder and then have the template and static folder as in the PR?

**Review by d-coder111 — APPROVED** [review]

**Pull request merged**
