### PR TITLE
added greedySearch in cpp

### PR DESCRIPTION
**Pull request by Surieya**

### CODE REVIEW

**Comment by Surieya** [comment]
kindly check and accept my PR @d-coder111

**Review by d-coder111 — CHANGES_REQUESTED** [review]
delete this empty file.

**Review by d-coder111 — APPROVED** [review]
Looks ok..star the repo to support us.

**Comment by Surieya** [comment]
done @d-coder111

**Comment by d-coder111** [comment]
Hey @Surieya..raise a new pr by creating a new branch..u have added redundant files..one of them is empty file.

**Pull request closed without merging**
