### PR TITLE
added my contribution ~

### PR DESCRIPTION
**Pull request by mintera10**
created a simple alarm clock using python and here is the working video ~

https://github.com/user-attachments/assets/b1d9720a-e0ee-4d5c-955d-7b0553daae94

### CODE REVIEW

**Review by d-coder111 — APPROVED** [review]
looks ok👍..Kindly consider starring the repository to show your support🌟👍. Any meaningful contributions are welcomed!😊...for python check this one also-https://github.com/d-coder111/SpectrumOfPython

**Comment by mintera10** [comment]
Sure :)

**Comment by d-coder111** [comment]
Hey @mintera10 you can add your python project in the above mentioned repo also.. as that's specifically designed for python lovers and that's also hacktoberfest accepted repo.
happy coding.. happy learning 😊👍.

**Comment by mintera10** [comment]
Alright, will do!

**Pull request merged**
