### PR TITLE
Adding sortVowels.cpp

### PR DESCRIPTION
**Pull request by AbdullahIshtiaqq**

### CODE REVIEW

**Review by d-coder111 — CHANGES_REQUESTED** [review]
Rename the file

**Comment by AbdullahIshtiaqq** [comment]
What should be the name of the file? @d-coder111

**Comment by d-coder111** [comment]
> What should be the name of the file? @d-coder111

just name based on what the program is doing.

**Comment by AbdullahIshtiaqq** [comment]
> > What should be the name of the file? @d-coder111
> 
> just name based on what the program is doing.

It is already sortVowels.cpp, which actually program is doing:)

**Comment by d-coder111** [comment]
> > > What should be the name of the file? @d-coder111
> > 
> > 
> > just name based on what the program is doing.
> 
> It is already sortVowels.cpp, which actually program is doing:)

ok cool.

**Review by d-coder111 — APPROVED** [review]

**Comment by d-coder111** [comment]
Hey @AbdullahIshtiaqq ,
Do support the repo by starring it and you are welcome to contribute more in programs and web-development domain of this repo✌😊.

**Pull request merged**
