### PR TITLE
added reverseWords.java with main function

### PR DESCRIPTION
**Pull request by jenyyy4**

### CODE REVIEW

**Comment by jenyyy4** [comment]
@d-coder111 i have added the main function, please review it.

**Comment by d-coder111** [comment]
> @d-coder111 i have added the main function, please review it.

I have assigned N queen to the other person..plz do not add redundant program and add only the programs and not other file.
You can try adding different program or work on the web domain of the project.

**Comment by jenyyy4** [comment]
@d-coder111 i am adding only reverseWords.java
Previously i added NQueen but then i removed it.

**Comment by d-coder111** [comment]
Ok create a new pr..i will merge it and add only the program file not any other

**Pull request closed without merging**
